### ISSUE TITLE
search报错，并且style.css无法加载

### ISSUE THREAD

**Issue by 2ue** [artchen/hexo-theme-typescript#3]
Partial _partial/search does not exist. (in layout.ejs)
GET http://localhost:4000/css/style.css 

都是在本地启动服务，已经安装了作者你列出来的五个插件~

**Comment by artchen** [comment]
1. _partial/search已修复。这个文件之前删掉了，忘记在layout.ejs删引用。
2. style.css在根目录。http://localhost:4000/style.css

**Comment by zhuscat** [comment]
GET http://localhost:4000/style.css

无法获取资源。

看了一下 `hexo g` 的内容，有一个 `style.less`

插件都安装了（是安装在博客根目录下吧

**Comment by artchen** [comment]
less renderer应该是会默认找source下的less文件来compile，不知道为什么你们那里不是这样。
在主题的_config.xml里写明path应该可以解决：

```
# Less
less:
  compress: true
  paths: 
    - source
```

**Comment by playmyswift** [comment]
同样的问题 
```
# Less
less:
  compress: true
  paths: 
    - source
```
没用
